// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnAW0pzAnS3dgsyUmM_MpuKSbPH5mkA_Q',
    appId: '1:343622634281:web:51a09525fc9e96338a0538',
    messagingSenderId: '343622634281',
    projectId: 'gonput2-251a5',
    authDomain: 'gonput2-251a5.firebaseapp.com',
    storageBucket: 'gonput2-251a5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtXvJ4upUQaPI8T1L6kjpwYsnHX7-EDdc',
    appId: '1:343622634281:android:96fa2218e81199d38a0538',
    messagingSenderId: '343622634281',
    projectId: 'gonput2-251a5',
    storageBucket: 'gonput2-251a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwnl-m1tkmYM6m_uFdTR6gqR4-BPAhNQs',
    appId: '1:343622634281:ios:d271805a7d00b4da8a0538',
    messagingSenderId: '343622634281',
    projectId: 'gonput2-251a5',
    storageBucket: 'gonput2-251a5.appspot.com',
    iosClientId: '343622634281-v9vdq6dv0eev6ipcv8sq4984ugspt1ba.apps.googleusercontent.com',
    iosBundleId: 'com.example.gonput2',
  );
}
